services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: your_db_name
            POSTGRES_USER: your_db_user
            POSTGRES_PASSWORD: your_db_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    app:
        build: .
        environment:
            APP_SECRET: asupersecretstring
            DB_NAME: your_db_name
            DB_USER: your_db_user
            DB_PASSWORD: your_db_password
            DB_HOST: db
            DB_PORT: 5432
        ports:
            - "5000:5000"
        depends_on:
            - db
volumes:
    postgres_data: